---
- name: Validate WireGuard inputs
  import_tasks: validate.yml

- name: Configure Alpine package dependencies
  import_tasks: alpine.yml

- name: Configure kernel forwarding
  import_tasks: sysctl.yml

- name: Configure WireGuard
  import_tasks: wireguard.yml

- name: Configure nftables
  import_tasks: nftables.yml

- name: Configure services
  import_tasks: services.yml