---
- name: Restart wireguard
  service:
    name: "{{ wireguard_service_name }}"
    state: restarted

- name: Validate nftables configuration
  command: "nft --check --file {{ wireguard_nftables_config_path }}"
  changed_when: false
  listen: Reload nftables

- name: Apply nftables configuration
  command: "nft --file {{ wireguard_nftables_config_path }}"
  listen: Reload nftables